### ISSUE TITLE
The «Color» filter disappears on a «Brand» filter selection and vice versa

### ISSUE THREAD

**Issue by dmitry-fedyuk** [alleswunder2/issues#30]
![01](https://user-images.githubusercontent.com/83204/52018558-c7f12c80-2525-11e9-969d-994c25212ef3.png)

**Comment by 0xSaiyajin** [comment]
Issue fixed after colour attribute update for products which have "brand" attribute. Still working on "AllesWunder" brand.

![ColorFix](https://user-images.githubusercontent.com/13886709/52109277-fe09db80-260d-11e9-86e0-b6bb4b428a20.png)

**Comment by dmitry-fedyuk** [comment]
It seems to be fixed.
